name: log test

on: 
    workflow_dispatch:

jobs:
    log-test:
        runs-on: ubuntu latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: Run log test
              run: python log_test.py

            - name: Upload test log
              uses: actions/upload-artifact@v3
              with:
                name: weather-logs
                path: logs/weather_logging.log