name: Weather Script Every 5 Minutes

on:
    #schedule:
        #- cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    run-weather:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Upload log file
              uses: actions/upload-artifact@v4
              with:
                name: weather-logs
                path: logs/weather_logging.log

            - name: Run weather_logging_script.py
              env:
                OPENWEATHER_API_URL: ${{ secrets.OPENWEATHER_API_URL }}
                LVILLE_WEATHER_BASE_URL: ${{ secrets.LVILLE_WEATHER_BASE_URL }}
                LVILLE_USER_AGENT: ${{ secrets.LVILLE_USER_AGENT }}
                LVILLE_REFERER: ${{ secrets.LVILLE_REFERER }}
                DATABASE_USER: ${{ secrets.DATABASE_USER }}
                DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
              run: python weather_logging_script.py
