name: OW Weather Script Every Day

on:
    schedule:
        - cron: "30 16 * * *"
    workflow_dispatch:

jobs:
    run-weather:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run openweather_logging.py
              env:
                OW_API_URL: ${{ secrets.OW_API_URL }}
                OW_API_KEY: ${{ secrets.OW_API_KEY}}
                DATABASE_USER: ${{ secrets.DATABASE_USER }}
                DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
              run: python openweather_logging.py
            
            - name: Upload log file
              uses: actions/upload-artifact@v4
              with:
                name: openweather-logs
                path: logs/ow_logging.log