name: Weather Script Every 15 Minutes

on:
    schedule:
        - cron: "*/15 * * * *"
    workflow_dispatch:

jobs:
    run-weather:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run weather_logging_script.py
              env:
                OPENWEATHER_API_URL: https://api.openweathermap.org/data/2.5/weather?lat=40.2942&lon=-74.7247&appid=5ea0a017f483f25bd21c215fa555c809
                LVILLE_WEATHER_BASE_URL: https://owc.enterprise.earthnetworks.com/Data/GetData.ashx
                LVILLE_USER_AGENT: Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1
                LVILLE_REFERER: https://owc.enterprise.earthnetworks.com/Graphs/HourlyObs.aspx?aid=8334&pid=3&station_id=LWRTR&units=english&culture_id=en-US
                DATABASE_USER: postgres.tpciwzjsmjpozcirkcgs
                DATABASE_PASSWORD: qTe99ASyue1botOA
                DATABASE_PORT: 5432
                DATABASE_HOST: aws-0-us-east-1.pooler.supabase.com
                DATABASE_NAME: postgres
              run: python weather_logging_script.py
