name: Lville Weather Script Every Day

on:
    schedule:
        - cron: "30 16 * * *"
    workflow_dispatch:

jobs:
    run-weather:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run lvilleweather_logging.py
              env:
                LVILLE_WEATHER_BASE_URL: ${{ secrets.LVILLE_WEATHER_BASE_URL }}
                LVILLE_USER_AGENT: ${{ secrets.LVILLE_USER_AGENT }}
                LVILLE_REFERER: ${{ secrets.LVILLE_REFERER }}
                DATABASE_USER: ${{ secrets.DATABASE_USER }}
                DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
              run: python lvilleweather_logging.py
            
            - name: Upload log file
              uses: actions/upload-artifact@v4
              with:
                name: lvilleweather-logs
                path: logs/lvillew_logging.log