name: Solar Script Every Day

on:
    schedule:
        - cron: "30 16 * * *"
    workflow_dispatch:

jobs:
    run-solar:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run solar_logging.py
              env:
                SOLAR_CLIENT_ID: ${{ secrets.SOLAR_CLIENT_ID }}
                SOLAR_CLIENT_SECRET: ${{ secrets.SOLAR_CLIENT_SECRET }}
                REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                REFRESH_URL: ${{ secrets.REFRESH_URL }}
                SOLAR_API_URL: ${{ secrets.SOLAR_API_URL }}
                DATABASE_USER: ${{ secrets.DATABASE_USER }}
                DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
              run: python data_logging/solar_logging.py

            - name: Upload log file
              uses: actions/upload-artifact@v4
              with:
                name: solar-logs
                path: logs/solar_logging.log